# Generated by Django 3.2.3 on 2021-05-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('layout', models.CharField(blank=True, max_length=30, null=True)),
                ('condition', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('negotiable', models.BooleanField(blank=True, default=False, null=True)),
                ('trade', models.BooleanField(blank=True, default=False, null=True)),
                ('rgb', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('sold', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keycap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('profile', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Keycaps',
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(blank=True, max_length=30, null=True)),
                ('switch_type', models.CharField(blank=True, max_length=30, null=True)),
                ('spring_force', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount', models.IntegerField(blank=True, default=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Switches',
            },
        ),
    ]
