# Generated by Django 3.2.3 on 2021-05-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_alter_keyboard_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='rgb',
            new_name='RGB',
        ),
    ]
